In [28]:
import pandas as pd
import numpy as np

In [29]:
file1 = pd.read_csv('file1.csv')
file2 = pd.read_csv('file2.csv')
file3 = pd.read_csv('file3.csv')
file1

Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master   
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
...       ...         ...    ...                   ...   
4003      NaN         NaN    NaN                   NaN   
4004      NaN         NaN    NaN                   NaN   
4005      NaN         NaN    NaN                   NaN   
4006      NaN         NaN    NaN                   NaN   
4007      NaN         NaN    NaN                   NaN   

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0   
1                 697953.59%      0.0                  94.0   
2                1288743.17%  48767.0                 108.0   
3                 764586.18%      0.0                 106.0   
4                 536307.65%  36357.0                  68.0   
...                      ...      ...                   ...   
4003                     NaN      NaN                   NaN   
4004                     NaN      NaN                   NaN   
4005                     NaN      NaN                   NaN   
4006                     NaN      NaN                   NaN   
4007                     NaN      NaN                   NaN   

     Number of Open Complaints     Policy Type  Vehicle Class  \
0                       1/0/00   Personal Auto  Four-Door Car   
1                       1/0/00   Personal Auto  Four-Door Car   
2                       1/0/00   Personal Auto   Two-Door Car   
3                       1/0/00  Corporate Auto            SUV   
4                       1/0/00   Personal Auto  Four-Door Car   
...                        ...             ...            ...   
4003                       NaN             NaN            NaN   
4004                       NaN             NaN            NaN   
4005                       NaN             NaN            NaN   
4006                       NaN             NaN            NaN   
4007                       NaN             NaN            NaN   

      Total Claim Amount  
0               2.704934  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
...                  ...  
4003                 NaN  
4004                 NaN  
4005                 NaN  
4006                 NaN  
4007                 NaN  

[4008 rows x 11 columns]

In [19]:
display(file1.shape)
display(file2.shape)
display(file3.shape)

(4008, 11)

(996, 11)

(7070, 11)

In [8]:
display(file1.columns)
display(file2.columns)
display(file3.columns)

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Total Claim Amount', 'Policy Type', 'Vehicle Class'],
      dtype='object')

Index(['Customer', 'State', 'Customer Lifetime Value', 'Education', 'Gender',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Total Claim Amount', 'Vehicle Class'],
      dtype='object')

In [30]:
file1.columns == file2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False])

In [31]:
cols1=[]
for c in file1.columns:
    cols1.append(c.lower())
file1.columns=cols1

# Similarly for the other dataframe:
cols2=[]
for c in file2.columns:
    cols2.append(c.lower())
file2.columns=cols2

# Similarly for the third dataframe:
cols3=[]
for c in file3.columns:
    cols3.append(c.lower())
file3.columns=cols3

file1 = file1.rename(columns={ 'st':'state', 'customer lifetime value':'customer_lifetime_value',
                              'monthly premium auto': 'monthly_premium_auto', 
                             'number of open complaints': 'number_of_open_complaints', 
                             'policy type': 'policy_type', 'vehicle class': 'vehicle_class', 
                             'total claim amount': 'total_claim_amount'})


file2 = file2.rename(columns={ 'st':'state', 'customer lifetime value':'customer_lifetime_value',
                              'monthly premium auto': 'monthly_premium_auto', 
                             'number of open complaints': 'number_of_open_complaints', 
                             'policy type': 'policy_type', 'vehicle class': 'vehicle_class', 
                             'total claim amount': 'total_claim_amount'})


file3 = file3.rename(columns={ 'customer lifetime value':'customer_lifetime_value',
                              'monthly premium auto': 'monthly_premium_auto', 
                             'number of open complaints': 'number_of_open_complaints', 
                             'policy type': 'policy_type', 'vehicle class': 'vehicle_class', 
                             'total claim amount': 'total_claim_amount'})



In [21]:
display(file1)

customer       state gender             education  \
0     RB50392  Washington    NaN                Master   
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
...       ...         ...    ...                   ...   
4003      NaN         NaN    NaN                   NaN   
4004      NaN         NaN    NaN                   NaN   
4005      NaN         NaN    NaN                   NaN   
4006      NaN         NaN    NaN                   NaN   
4007      NaN         NaN    NaN                   NaN   

     customer_lifetime_value   income  monthly_premium_auto  \
0                        NaN      0.0                1000.0   
1                 697953.59%      0.0                  94.0   
2                1288743.17%  48767.0                 108.0   
3                 764586.18%      0.0                 106.0   
4                 536307.65%  36357.0                  68.0   
...                      ...      ...                   ...   
4003                     NaN      NaN                   NaN   
4004                     NaN      NaN                   NaN   
4005                     NaN      NaN                   NaN   
4006                     NaN      NaN                   NaN   
4007                     NaN      NaN                   NaN   

     number_of_open_complaints     policy_type  vehicle_class  \
0                       1/0/00   Personal Auto  Four-Door Car   
1                       1/0/00   Personal Auto  Four-Door Car   
2                       1/0/00   Personal Auto   Two-Door Car   
3                       1/0/00  Corporate Auto            SUV   
4                       1/0/00   Personal Auto  Four-Door Car   
...                        ...             ...            ...   
4003                       NaN             NaN            NaN   
4004                       NaN             NaN            NaN   
4005                       NaN             NaN            NaN   
4006                       NaN             NaN            NaN   
4007                       NaN             NaN            NaN   

      total_claim_amount  
0               2.704934  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
...                  ...  
4003                 NaN  
4004                 NaN  
4005                 NaN  
4006                 NaN  
4007                 NaN  

[4008 rows x 11 columns]

In [32]:
file1.columns == file2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False])

In [26]:
file2.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='object')

In [33]:
file2 = file2[['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount']]
file3 = file3[['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount']]

In [34]:
file1.columns == file2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [35]:
file1.columns == file3.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [66]:
df1 = file1.copy()

In [68]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   customer                   1071 non-null   object 
 1   state                      1071 non-null   object 
 2   gender                     954 non-null    object 
 3   education                  1071 non-null   object 
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object 
 8   policy_type                1071 non-null   object 
 9   vehicle_class              1071 non-null   object 
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(4), object(7)
memory usage: 344.6+ KB


In [67]:
df1['customer_lifetime_value'] = df1['customer_lifetime_value'].str.replace('%', '').astype(float)

In [69]:
df1['customer_lifetime_value'] = df1['customer_lifetime_value']/100

In [70]:
df1['customer_lifetime_value']

0              NaN
1        6979.5359
2       12887.4317
3        7645.8618
4        5363.0765
           ...    
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: customer_lifetime_value, Length: 4008, dtype: float64

In [71]:
file1['customer_lifetime_value'] = file1['customer_lifetime_value'].str.replace('%', '').astype(float)

In [72]:
file1['customer_lifetime_value'] = file1['customer_lifetime_value']/100

In [73]:
file2['customer_lifetime_value'] = file2['customer_lifetime_value'].str.replace('%', '').astype(float)

In [74]:
file2['customer_lifetime_value'] = file2['customer_lifetime_value']/100

In [75]:
file2['customer_lifetime_value']

0       3239.1247
1       4626.8011
2       8997.0402
3      25807.0630
4       3808.1221
          ...    
991     8471.4175
992     5431.2191
993     5689.6441
994     3686.7238
995     3992.5839
Name: customer_lifetime_value, Length: 996, dtype: float64

In [85]:
data = pd.concat([file1,file2,file3], axis=0)

In [80]:
data

customer       state gender  customer_lifetime_value   income  \
0     RB50392  Washington    NaN                      NaN      0.0   
1     QZ44356     Arizona      F              6979.535900      0.0   
2     AI49188      Nevada      F             12887.431700  48767.0   
3     WW63253  California      M              7645.861800      0.0   
4     GA49547  Washington      M              5363.076500  36357.0   
...       ...         ...    ...                      ...      ...   
7065  LA72316  California      M             23405.987980  71941.0   
7066  PK87824  California      F              3096.511217  21604.0   
7067  TD14365  California      M              8163.890428      0.0   
7068  UP19263  California      M              7524.442436  21941.0   
7069  Y167826  California      M              2611.836866      0.0   

      monthly_premium_auto     policy_type  vehicle_class  total_claim_amount  
0                   1000.0   Personal Auto  Four-Door Car            2.704934  
1                     94.0   Personal Auto  Four-Door Car         1131.464935  
2                    108.0   Personal Auto   Two-Door Car          566.472247  
3                    106.0  Corporate Auto            SUV          529.881344  
4                     68.0   Personal Auto  Four-Door Car           17.269323  
...                    ...             ...            ...                 ...  
7065                  73.0   Personal Auto  Four-Door Car          198.234764  
7066                  79.0  Corporate Auto  Four-Door Car          379.200000  
7067                  85.0  Corporate Auto  Four-Door Car          790.784983  
7068                  96.0   Personal Auto  Four-Door Car          691.200000  
7069                  77.0  Corporate Auto   Two-Door Car          369.600000  

[12074 rows x 9 columns]

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12074 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   customer                   9137 non-null   object 
 1   state                      9137 non-null   object 
 2   gender                     9015 non-null   object 
 3   education                  9137 non-null   object 
 4   customer_lifetime_value    9130 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object 
 8   policy_type                9137 non-null   object 
 9   vehicle_class              9137 non-null   object 
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(4), object(7)
memory usage: 1.1+ MB


In [86]:
data = data.drop(['education', 'number_of_open_complaints'], axis =1)

In [79]:
data.head()

customer       state gender  customer_lifetime_value   income  \
0  RB50392  Washington    NaN                      NaN      0.0   
1  QZ44356     Arizona      F                6979.5359      0.0   
2  AI49188      Nevada      F               12887.4317  48767.0   
3  WW63253  California      M                7645.8618      0.0   
4  GA49547  Washington      M                5363.0765  36357.0   

   monthly_premium_auto     policy_type  vehicle_class  total_claim_amount  
0                1000.0   Personal Auto  Four-Door Car            2.704934  
1                  94.0   Personal Auto  Four-Door Car         1131.464935  
2                 108.0   Personal Auto   Two-Door Car          566.472247  
3                 106.0  Corporate Auto            SUV          529.881344  
4                  68.0   Personal Auto  Four-Door Car           17.269323

In [87]:
data = data.drop_duplicates()

In [82]:
data

customer       state gender  customer_lifetime_value   income  \
0     RB50392  Washington    NaN                      NaN      0.0   
1     QZ44356     Arizona      F              6979.535900      0.0   
2     AI49188      Nevada      F             12887.431700  48767.0   
3     WW63253  California      M              7645.861800      0.0   
4     GA49547  Washington      M              5363.076500  36357.0   
...       ...         ...    ...                      ...      ...   
7065  LA72316  California      M             23405.987980  71941.0   
7066  PK87824  California      F              3096.511217  21604.0   
7067  TD14365  California      M              8163.890428      0.0   
7068  UP19263  California      M              7524.442436  21941.0   
7069  Y167826  California      M              2611.836866      0.0   

      monthly_premium_auto     policy_type  vehicle_class  total_claim_amount  
0                   1000.0   Personal Auto  Four-Door Car            2.704934  
1                     94.0   Personal Auto  Four-Door Car         1131.464935  
2                    108.0   Personal Auto   Two-Door Car          566.472247  
3                    106.0  Corporate Auto            SUV          529.881344  
4                     68.0   Personal Auto  Four-Door Car           17.269323  
...                    ...             ...            ...                 ...  
7065                  73.0   Personal Auto  Four-Door Car          198.234764  
7066                  79.0  Corporate Auto  Four-Door Car          379.200000  
7067                  85.0  Corporate Auto  Four-Door Car          790.784983  
7068                  96.0   Personal Auto  Four-Door Car          691.200000  
7069                  77.0  Corporate Auto   Two-Door Car          369.600000  

[9135 rows x 9 columns]

In [88]:
data['income_check'] = data['income']>0

In [89]:
data = data[data['income_check']==True]

In [91]:
data = data.drop(['income_check'], axis =1)
data

customer       state gender  customer_lifetime_value   income  \
2     AI49188      Nevada      F             12887.431700  48767.0   
4     GA49547  Washington      M              5363.076500  36357.0   
5     OC83172      Oregon      F              8256.297800  62902.0   
6     XZ87318      Oregon      F              5380.898600  55350.0   
8     DY87989      Oregon      M             24127.504000  14072.0   
...       ...         ...    ...                      ...      ...   
7063  TF56202  California      M              5032.165498  66367.0   
7064  YM19146  California      F              4100.398533  47761.0   
7065  LA72316  California      M             23405.987980  71941.0   
7066  PK87824  California      F              3096.511217  21604.0   
7068  UP19263  California      M              7524.442436  21941.0   

      monthly_premium_auto     policy_type  vehicle_class  total_claim_amount  
2                    108.0   Personal Auto   Two-Door Car          566.472247  
4                     68.0   Personal Auto  Four-Door Car           17.269323  
5                     69.0   Personal Auto   Two-Door Car          159.383042  
6                     67.0  Corporate Auto  Four-Door Car          321.600000  
8                     71.0  Corporate Auto  Four-Door Car          511.200000  
...                    ...             ...            ...                 ...  
7063                  64.0   Personal Auto   Two-Door Car          307.200000  
7064                 104.0   Personal Auto  Four-Door Car          541.282007  
7065                  73.0   Personal Auto  Four-Door Car          198.234764  
7066                  79.0  Corporate Auto  Four-Door Car          379.200000  
7068                  96.0   Personal Auto  Four-Door Car          691.200000  

[6840 rows x 9 columns]